# Generated by Django 2.1.5 on 2020-04-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=120)),
                ('Picture', models.ImageField(blank=True, height_field=100, null=True, upload_to='covers/%Y/%m/%D/', width_field=100)),
                ('Description', models.TextField(blank=True)),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=100)),
                ('Date', models.DateField(blank=True)),
                ('URL', models.URLField(blank=True)),
                ('Comments', models.TextField(blank=True)),
            ],
        ),
    ]
