# Generated by Django 2.1.5 on 2020-04-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.URLField(blank=True)),
                ('Picture_URL', models.URLField(blank=True, max_length=2000)),
                ('Description', models.TextField(blank=True)),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=100)),
                ('Date', models.DateField(blank=True)),
                ('URL', models.URLField(blank=True)),
            ],
        ),
    ]
