# Generated by Django 2.1.5 on 2020-04-26 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=120)),
                ('Picture_URL', models.URLField(blank=True, max_length=2000, null=True)),
                ('Description', models.TextField(blank=True)),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('URL', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
